import { Router } from "express";
import PDFDocument from "pdfkit";

const router = Router();

/**
 * POST /api/export-pdf
 * Body: JSON { analysis, resumeText, jobDescription }
 * Returns: PDF binary stream
 */
router.post("/export-pdf", async (req, res, next) => {
  try {
    const { analysis, jobDescription } = req.body;
    if (!analysis) {
      return res.status(400).json({ error: "No analysis data provided." });
    }

    const doc = new PDFDocument({ margin: 50, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="resume-analysis-${Date.now()}.pdf"`,
    );
    doc.pipe(res);

    // ─── Header ────────────────────────────────────────────────────────────────
    doc
      .fillColor("#1e40af")
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("AI Resume Analysis Report", { align: "center" });

    doc
      .moveDown(0.3)
      .fillColor("#64748b")
      .fontSize(10)
      .font("Helvetica")
      .text(`Generated on ${new Date().toLocaleString()}`, { align: "center" });

    doc.moveDown(1);
    drawDivider(doc);

    // ─── Candidate Info ─────────────────────────────────────────────────────────
    const info = analysis.candidateInfo || {};
    section(doc, "Candidate Information");
    infoRow(doc, "Name", info.name);
    infoRow(doc, "Email", info.email);
    infoRow(doc, "Phone", info.phone);
    infoRow(doc, "Location", info.location);

    if (info.summary) {
      doc
        .moveDown(0.5)
        .fillColor("#374151")
        .fontSize(10)
        .font("Helvetica")
        .text(info.summary);
    }
    doc.moveDown(1);

    // ─── Match Score ────────────────────────────────────────────────────────────
    section(doc, "Match Score");
    const score = analysis.matchScore ?? 0;
    const scoreColor =
      score >= 75 ? "#16a34a" : score >= 50 ? "#d97706" : "#dc2626";
    doc
      .fillColor(scoreColor)
      .fontSize(36)
      .font("Helvetica-Bold")
      .text(`${score}%`, { align: "center" });
    doc
      .moveDown(0.5)
      .fillColor("#64748b")
      .fontSize(10)
      .font("Helvetica")
      .text(
        score >= 75
          ? "Strong Match — Great candidate for this role"
          : score >= 50
            ? "Moderate Match — Some gaps need to be addressed"
            : "Weak Match — Significant gaps identified",
        { align: "center" },
      );
    doc.moveDown(1);

    // ─── Skills ─────────────────────────────────────────────────────────────────
    if (analysis.matchingSkills?.length) {
      section(doc, `Matching Skills (${analysis.matchingSkills.length})`);
      doc
        .fillColor("#16a34a")
        .fontSize(10)
        .font("Helvetica")
        .text(analysis.matchingSkills.join("  •  "));
      doc.moveDown(1);
    }

    if (analysis.missingSkills?.length) {
      section(doc, `Missing Skills (${analysis.missingSkills.length})`);
      doc
        .fillColor("#dc2626")
        .fontSize(10)
        .font("Helvetica")
        .text(analysis.missingSkills.join("  •  "));
      doc.moveDown(1);
    }

    // ─── Suggestions ────────────────────────────────────────────────────────────
    if (analysis.suggestions?.length) {
      section(doc, "Improvement Suggestions");
      analysis.suggestions.forEach((suggestion, i) => {
        doc
          .fillColor("#374151")
          .fontSize(10)
          .font("Helvetica")
          .text(`${i + 1}. ${suggestion}`, { indent: 10 });
        doc.moveDown(0.4);
      });
      doc.moveDown(0.5);
    }

    // ─── Job Description ────────────────────────────────────────────────────────
    if (jobDescription) {
      section(doc, "Job Description");
      doc
        .fillColor("#374151")
        .fontSize(9)
        .font("Helvetica")
        .text(
          jobDescription.slice(0, 1500) +
            (jobDescription.length > 1500 ? "..." : ""),
        );
    }

    // ─── Footer ─────────────────────────────────────────────────────────────────
    doc.moveDown(2);
    drawDivider(doc);
    doc
      .fillColor("#94a3b8")
      .fontSize(8)
      .font("Helvetica")
      .text("Generated by AI Resume Analyzer • Powered by Google Gemini", {
        align: "center",
      });

    doc.end();
  } catch (err) {
    next(err);
  }
});

function section(doc, title) {
  doc.fillColor("#1e40af").fontSize(13).font("Helvetica-Bold").text(title);
  doc.moveDown(0.4);
}

function infoRow(doc, label, value) {
  if (!value || value === "Not found") return;
  doc
    .fillColor("#64748b")
    .fontSize(10)
    .font("Helvetica-Bold")
    .text(`${label}: `, { continued: true })
    .fillColor("#374151")
    .font("Helvetica")
    .text(value);
  doc.moveDown(0.2);
}

function drawDivider(doc) {
  doc
    .moveTo(50, doc.y)
    .lineTo(545, doc.y)
    .strokeColor("#e2e8f0")
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.8);
}

export default router;
